Q. Create a Persistent Volume called log-volume. 
It should make use of a storage class name manual. 
It should use RWX as the access mode and have a size of 1Gi. 
The volume should use the hostPath /opt/volume/nginx

Next, create a PVC called log-claim requesting a minimum of 200Mi of storage. 
This PVC should bind to log-volume.

Mount this in a pod called logger at the location /var/www/nginx. This pod should use the image nginx:alpine.


$cat pv.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteMany
  hostPath: 
    path: /opt/volume/nginx
	
$cat pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: manual
  

$ kubectl apply -f pv.yaml
$ kubectl apply -f pvc.yaml

$ kubectl get pv
NAME         CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM               STORAGECLASS   VOLUMEATTRIBUTESCLASS   REASON   AGE
log-volume   1Gi        RWX            Retain           Bound    default/log-claim   manual         <unset>                          15m

$ kubectl get pvc
NAME        STATUS   VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
log-claim   Bound    log-volume   1Gi        RWX            manual         <unset>                 2m8s

$ cat pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  volumes: 
    - name: log
      persistentVolumeClaim: 
        claimName: log-name
  containers:
  - image: nginx:alpine
    name: logger
    resources: {}
    volumeMounts:
      - name: log
        mountPath: /var/www/nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

$ kubectl apply -f pod.yaml
